version: '3.7'

services:
  minio_server:
    image: minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    command: server --console-address ":120001" /data
    env_file: .env
    restart: always
